# Generated by Django 2.1.7 on 2019-03-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_waterbodyreport_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodyreport',
            name='pincode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Region'),
        ),
    ]
