# Generated by Django 2.1.7 on 2019-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_waterbodyreport_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_path',
            field=models.FileField(null=True, upload_to='reports/user_<django.db.models.fields.related.ForeignKey>/user_<django.db.models.fields.related.ForeignKey>/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='waterbodyreport',
            name='image_path',
            field=models.ImageField(null=True, upload_to='images/user_<django.db.models.fields.related.ForeignKey>/%Y/%m/%d'),
        ),
    ]
