# Generated by Django 2.1.7 on 2019-03-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20190302_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1, null=True, verbose_name=(('M', 'Male'), ('F', 'Female'), ('O', 'Other'))),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(max_length=1, null=True, verbose_name=(('P', 'Person'), ('H', 'Hospital'), ('D', 'Dispensary'), ('L', 'Lab'))),
        ),
    ]
