# Generated by Django 2.1.7 on 2019-03-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20190302_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
