# Generated by Django 2.1.7 on 2019-03-02 22:27

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20190302_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lab',
            name='certificate',
            field=models.ImageField(upload_to=db.models.lab_certi_path),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.FloatField(default=25.3176),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.FloatField(default=82.9739),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_path',
            field=models.FileField(null=True, upload_to=db.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(max_length=1, null=True, verbose_name=(('P', 'Person'), ('H', 'Hospital'), ('L', 'Lab'))),
        ),
        migrations.AlterField(
            model_name='waterbodyreport',
            name='image_path',
            field=models.ImageField(null=True, upload_to=db.models.user_image_path),
        ),
    ]
