# Generated by Django 2.1.7 on 2019-03-03 00:04

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20190303_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='certificate',
            field=models.ImageField(null=True, upload_to=db.models.lab_certi_path),
        ),
        migrations.AlterField(
            model_name='lab',
            name='govt_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
