# Generated by Django 2.1.7 on 2019-03-03 11:11

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190303_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('pincode', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('dengueBed', models.IntegerField(blank=True)),
                ('malariaBed', models.IntegerField(blank=True)),
                ('tuberculosisBed', models.IntegerField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('govt_id', models.CharField(blank=True, max_length=255)),
                ('adhaar', models.CharField(blank=True, max_length=255)),
                ('docRegNo', models.CharField(blank=True, max_length=255)),
                ('disease', models.CharField(blank=True, max_length=255)),
                ('hosName', models.CharField(blank=True, max_length=255)),
                ('HosReg', models.CharField(blank=True, max_length=255)),
                ('accreditation', models.CharField(blank=True, max_length=255)),
                ('report_upload', models.FileField(blank=True, null=True, upload_to=db.models.user_directory_path)),
                ('certi_upload', models.ImageField(blank=True, null=True, upload_to=db.models.lab_certi_path)),
                ('report_disease', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name=(('M', 'Male'), ('F', 'Female'), ('O', 'Other')))),
            ],
        ),
    ]
