# Generated by Django 2.1.7 on 2019-03-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20190303_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name')},
        ),
    ]
